[env:esp32dev]
platform = espressif32      ; We're using an ESP32 chip
board = esp32dev            ; Specifically the standard ESP32 dev board
framework = arduino         ; We code using the Arduino framework

monitor_speed = 115200      ; Serial monitor baud rate (for debugging)

lib_deps =
    paulstoffregen/OneWire @ ^2.3.8          ; 1-Wire protocol (required by DS18B20)
    milesburton/DallasTemperature @ ^3.11.0  ; Reads temperature from DS18B20
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4 ; Controls the LCD 16x2 via I2C
    knolleary/PubSubClient @ ^2.8            ; MQTT protocol for WiFi alerts
    mathworks/ThingSpeak @ ^2.0.0            ; Sends data to ThingSpeak dashboard
    greiman/SdFat @ ^2.2.0                   ; SD card library
    makuna/RTC @ ^2.3.5                 ; RTC clock library, to get timestamps in the sd card logging